#!/usr/bin/env bash
#
# setup.sh — Bootstrap the Infisical self-hosted instance.
#
# Prerequisites:
#   - Docker & Docker Compose installed
#   - 1Password CLI (`op`) installed and signed in
#   - This script must run on the target host (LXC or Docker host on PVE)
#
# Usage:
#   bash setup.sh              # Interactive — generates secrets, writes .env, starts stack
#   bash setup.sh --op         # Pulls/stores all values from/to 1Password automatically
#
# After first run:
#   1. Log in to http://<host-ip>:8080 and create admin account
#   2. Store admin credentials in 1Password (see SECURITY_CLEANUP.md)
#   3. Create project "homelab", environment "prod"
#   4. Add a reverse proxy entry in NPM for infisical.aser.dk → <host-ip>:8080

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

USE_OP=false
[[ "${1:-}" == "--op" ]] && USE_OP=true

# ── Helpers ───────────────────────────────────────────────────

generate_hex() {
  openssl rand -hex "${1:-16}"
}

generate_password() {
  # 24-char alphanumeric (safe for DB passwords, no shell-quoting issues)
  openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c "${1:-24}"
}

log() {
  echo "[infisical-setup] $*"
}

# ── Pre-flight checks ────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  echo "ERROR: docker is not installed. Run install_docker_debian.sh first." >&2
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo "ERROR: docker compose plugin not found." >&2
  exit 1
fi

if [[ -f .env ]]; then
  log ".env already exists — skipping secret generation."
  log "To regenerate, remove .env and re-run this script."
  log ""
  log "Starting Infisical stack..."
  docker compose up -d
  log "Done. Infisical is available at http://$(hostname -I | awk '{print $1}'):8080"
  exit 0
fi

# ── Generate secrets ──────────────────────────────────────────

log "Generating secrets..."

ENCRYPTION_KEY=$(generate_hex 16)
AUTH_SECRET=$(generate_hex 16)
DB_USERNAME="infisical"
DB_PASSWORD=$(generate_password 24)
DB_NAME="infisical"
SITE_URL="https://infisical.aser.dk"

# ── Optionally store in 1Password ─────────────────────────────

if $USE_OP; then
  if ! command -v op &>/dev/null; then
    echo "ERROR: 1Password CLI (op) is not installed." >&2
    echo "  Install: winget install AgileBits.1Password.CLI  (or apt install 1password-cli)" >&2
    exit 1
  fi

  log "Storing Infisical credentials in 1Password vault 'Homelab'..."

  # Admin login item (placeholder — update after first login)
  op item create \
    --category=login \
    --vault="Homelab" \
    --title="Infisical – admin" \
    --url="$SITE_URL" \
    username="admin@aser.dk" \
    password="<set-after-first-login>" \
    --tags="homelab,infisical,security-cleanup-2026" \
    2>/dev/null || log "  (Item 'Infisical – admin' may already exist — skipping)"

  # Database credentials
  op item create \
    --category=database \
    --vault="Homelab" \
    --title="Infisical – postgres" \
    username="$DB_USERNAME" \
    password="$DB_PASSWORD" \
    hostname="localhost" \
    port="5432" \
    database="$DB_NAME" \
    --tags="homelab,infisical,security-cleanup-2026" \
    2>/dev/null || log "  (Item 'Infisical – postgres' may already exist — skipping)"

  # Encryption secrets
  op item create \
    --category=password \
    --vault="Homelab" \
    --title="Infisical – encryption key" \
    password="$ENCRYPTION_KEY" \
    notesPlain="ENCRYPTION_KEY for Infisical at-rest encryption. Do NOT rotate without re-encrypting the vault." \
    --tags="homelab,infisical,security-cleanup-2026" \
    2>/dev/null || log "  (Item 'Infisical – encryption key' may already exist — skipping)"

  op item create \
    --category=password \
    --vault="Homelab" \
    --title="Infisical – auth secret" \
    password="$AUTH_SECRET" \
    notesPlain="AUTH_SECRET for Infisical JWT signing." \
    --tags="homelab,infisical,security-cleanup-2026" \
    2>/dev/null || log "  (Item 'Infisical – auth secret' may already exist — skipping)"

  log "1Password items created."
fi

# ── Write .env ────────────────────────────────────────────────

log "Writing .env file..."

cat > .env <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit this file.

ENCRYPTION_KEY=${ENCRYPTION_KEY}
AUTH_SECRET=${AUTH_SECRET}

DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}

SITE_URL=${SITE_URL}
EOF

chmod 600 .env
log ".env written (mode 600)."

# ── Start the stack ───────────────────────────────────────────

log "Pulling images..."
docker compose pull

log "Starting Infisical stack..."
docker compose up -d

log ""
log "============================================"
log "  Infisical is starting up."
log "  UI: http://$(hostname -I | awk '{print $1}'):8080"
log ""
log "  Next steps:"
log "  1. Open the UI and create your admin account"
log "  2. Store the admin credentials in 1Password"
log "     (vault: Homelab, name: Infisical – admin)"
log "  3. Create project 'homelab', environment 'prod'"
log "  4. Add NPM proxy entry: infisical.aser.dk → this host:8080"
log "  5. Generate a TLS cert:"
log "     cd ../proxy && bash generate-certs.sh infisical"
log "============================================"
